// Generated by https://quicktype.io

export interface Country {
  name: Name;
  tld: string[];
  cca2: string;
  ccn3: string;
  cca3: string;
  cioc: string;
  independent: boolean;
  status: string;
  unMember: boolean;
  currencies: Currencies;
  idd: Idd;
  capital: string[];
  altSpellings: string[];
  region: string;
  subregion: string;
  languages: Languages;
  translations: { [key: string]: Translation };
  latlng: number[];
  landlocked: boolean;
  borders?: string[];
  area: number;
  demonyms: Demonyms;
  flag: string;
  maps: Maps;
  population: number;
  gini?: { [key: string]: number };
  fifa: string;
  car: Car;
  timezones: string[];
  continents: string[];
  flags: Flags;
  coatOfArms: CoatOfArms;
  startOfWeek: string;
  capitalInfo: CapitalInfo;
  postalCode?: PostalCode;
}

export interface CapitalInfo {
  latlng: number[];
}

export interface Car {
  signs: string[];
  side: string;
}

export interface CoatOfArms {
  png?: string;
  svg?: string;
}

export interface Currencies {
  AED?: Clp;
  AFN?: Clp;
  ALL?: Clp;
  AMD?: Clp;
  ANG?: Clp;
  AOA?: Clp;
  ARS?: Clp;
  AUD?: Clp;
  AWG?: Clp;
  AZN?: Clp;
  BAM?: Clp;
  BBD?: Clp;
  BDT?: Clp;
  BGN?: Clp;
  BHD?: Clp;
  BIF?: Clp;
  BMD?: Clp;
  BND?: Clp;
  BOB?: Clp;
  BRL?: Clp;
  BSD?: Clp;
  BTN?: Clp;
  BWP?: Clp;
  BYN?: Clp;
  BZD?: Clp;
  CAD?: Clp;
  CHF?: Clp;
  CLP?: Clp;
  CNY?: Clp;
  COP?: Clp;
  CRC?: Clp;
  CUC?: Clp;
  CUP?: Clp;
  CVE?: Clp;
  CZK?: Clp;
  DJF?: Clp;
  DKK?: Clp;
  DOP?: Clp;
  DZD?: Clp;
  EGP?: Clp;
  ERN?: Clp;
  ETB?: Clp;
  EUR?: Clp;
  FJD?: Clp;
  FKP?: Clp;
  GBP?: Clp;
  GEL?: Clp;
  GHS?: Clp;
  GIP?: Clp;
  GMD?: Clp;
  GNF?: Clp;
  GTQ?: Clp;
  GYD?: Clp;
  HKD?: Clp;
  HNL?: Clp;
  HRK?: Clp;
  HTG?: Clp;
  HUF?: Clp;
  IDR?: Clp;
  ILS?: Clp;
  INR?: Clp;
  IQD?: Clp;
  IRR?: Clp;
  ISK?: Clp;
  JMD?: Clp;
  JOD?: Clp;
  JPY?: Clp;
  KES?: Clp;
  KGS?: Clp;
  KHR?: Clp;
  KMF?: Clp;
  KPW?: Clp;
  KRW?: Clp;
  KWD?: Clp;
  KYD?: Clp;
  KZT?: Clp;
  LAK?: Clp;
  LBP?: Clp;
  LKR?: Clp;
  LRD?: Clp;
  LSL?: Clp;
  LTL?: Clp;
  LYD?: Clp;
  MAD?: Clp;
  MDL?: Clp;
  MGA?: Clp;
  MKD?: Clp;
  MMK?: Clp;
  MNT?: Clp;
  MOP?: Clp;
  MRO?: Clp;
  MUR?: Clp;
  MVR?: Clp;
  MWK?: Clp;
  MXN?: Clp;
  MYR?: Clp;
  MZN?: Clp;
  NAD?: Clp;
  NGN?: Clp;
  NIO?: Clp;
  NOK?: Clp;
  NPR?: Clp;
  NZD?: Clp;
  OMR?: Clp;
  PAB?: Clp;
  PEN?: Clp;
  PGK?: Clp;
  PHP?: Clp;
  PKR?: Clp;
  PLN?: Clp;
  PYG?: Clp;
  QAR?: Clp;
  RON?: Clp;
  RSD?: Clp;
  RUB?: Clp;
  RWF?: Clp;
  SAR?: Clp;
  SBD?: Clp;
  SCR?: Clp;
  SDG?: Clp;
  SEK?: Clp;
  SGD?: Clp;
  SLL?: Clp;
  SOS?: Clp;
  SRD?: Clp;
  SSP?: Clp;
  SYP?: Clp;
  SZL?: Clp;
  THB?: Clp;
  TJS?: Clp;
  TMT?: Clp;
  TND?: Clp;
  TOP?: Clp;
  TRY?: Clp;
  TTD?: Clp;
  TWD?: Clp;
  TZS?: Clp;
  UAH?: Clp;
  UGX?: Clp;
  USD?: Clp;
  UYU?: Clp;
  UZS?: Clp;
  VEF?: Clp;
  VES?: Clp;
  VND?: Clp;
  VUV?: Clp;
  WST?: Clp;
  XAF?: Clp;
  XCD?: Clp;
  XOF?: Clp;
  XPF?: Clp;
  YER?: Clp;
  ZAR?: Clp;
  ZMW?: Clp;
  ZWD?: Clp;
  STN?: Clp;
  ZWL?: Clp;
  CDF?: Clp;
  MRU?: Clp;
}

export interface Clp {
  name: string;
  symbol: string;
}

export interface Demonyms {
  eng: Eng;
  fra: Eng;
}

export interface Eng {
  f: string;
  m: string;
}

export interface Flags {
  png: string;
  svg: string;
  alt?: string;
}

export interface Idd {
  root: string;
  suffixes: string[];
}

export interface Languages {
  afr?: string;
  amh?: string;
  ara?: string;
  arc?: string;
  aym?: string;
  aze?: string;
  ben?: string;
  ber?: string;
  bjz?: string;
  bwg?: string;
  ckb?: string;
  crs?: string;
  deu?: string;
  div?: string;
  dzo?: string;
  eng?: string;
  fas?: string;
  fil?: string;
  fra?: string;
  grn?: string;
  hat?: string;
  heb?: string;
  her?: string;
  hgm?: string;
  hin?: string;
  hye?: string;
  ind?: string;
  ita?: string;
  jam?: string;
  jpn?: string;
  kal?: string;
  kat?: string;
  kaz?: string;
  kck?: string;
  khi?: string;
  khm?: string;
  kin?: string;
  kir?: string;
  kon?: string;
  kor?: string;
  kwn?: string;
  lao?: string;
  lin?: string;
  loz?: string;
  lua?: string;
  mey?: string;
  mfe?: string;
  mlg?: string;
  mon?: string;
  msa?: string;
  mya?: string;
  nbl?: string;
  ndc?: string;
  nde?: string;
  ndo?: string;
  nep?: string;
  nld?: string;
  nso?: string;
  nya?: string;
  pap?: string;
  por?: string;
  pov?: string;
  prs?: string;
  pus?: string;
  que?: string;
  run?: string;
  rus?: string;
  sag?: string;
  sin?: string;
  sna?: string;
  som?: string;
  sot?: string;
  spa?: string;
  ssw?: string;
  swa?: string;
  tam?: string;
  tet?: string;
  tgk?: string;
  tha?: string;
  tir?: string;
  toi?: string;
  tsn?: string;
  tso?: string;
  tuk?: string;
  tur?: string;
  urd?: string;
  uzb?: string;
  ven?: string;
  vie?: string;
  xho?: string;
  zdj?: string;
  zho?: string;
  zib?: string;
  zul?: string;
}

export interface Maps {
  googleMaps: string;
  openStreetMaps: string;
}

export interface Name {
  common: string;
  official: string;
  nativeName: NativeName;
}

export interface NativeName {
  ara?: Translation;
  spa?: Translation;
  ita?: Translation;
  eng?: Translation;
}

export interface Translation {
  official: string;
  common: string;
}

export interface PostalCode {
  format: string;
  regex: string;
}
